version: "1"
rules:
  - base: master
    upstream: matrix-profile-foundation:master
    mergeMethod: hardreset
  - base: develop
    upstream: matrix-profile-foundation:develop
    mergeMethod: hardreset
